import { setupBookingCtaSheen } from './features/booking-cta-sheen';
import { setupBookingDockLayout } from './features/booking-dock-layout';
import { setupCountdown } from './features/countdown';
import { setupHeroIntroMotion } from './features/hero-intro-motion';
import { setupPieceViewer } from './features/piece-viewer';
import { setupProposalReveal } from './features/proposal-reveal';
import { setupEfficientSmoothScroll } from './features/smooth-scroll';
import { setupTapSearchGuard } from './features/tap-search-guard';
import { setupVideoLoop } from './features/video-loop';
import { createRuntimeContext } from './shared/runtime';

const runtime = createRuntimeContext();
setupProposalReveal();
setupCountdown();
setupBookingDockLayout();
setupBookingCtaSheen(runtime);
setupHeroIntroMotion();
setupPieceViewer();
setupTapSearchGuard();
setupEfficientSmoothScroll(runtime);
setupVideoLoop(runtime);
